name: check and build

on: [pull_request]

jobs:
  build:
    name: Making it

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Getting node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: Looking for crap code
        run: npm run lint

      - name: Building prod
        run: npm run build

      - name: Packing build
        run: tar -czvf web-app.tar.gz dist/

      - name: Getting build hash
        run: sha256sum web-app.tar.gz | cut -d ' ' -f 1 | xxd -r -ps | base64 | sed 's,^,hash=,' >> $GITHUB_ENV

      - name: Commenting
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## https://pr-${{ github.event.number }}.morphic.ste-test.net/\n\n${{ env.hash }}'
            })

      - name: Uploading build
        run: curl -v -Fbuild=@web-app.tar.gz https://build.morphic.ste-test.net/build/upload/${{ github.event.number }}

      - name: Archiving prod
        uses: actions/upload-artifact@v2
        with:
          name: webapp-prod
          path: dist/




