name: morphic-i18n-central sync with crowdin

on:
  push:
    branches:
      - i18n-repo-push
  pull_request:
    branches:
      - i18n-repo-push
    

jobs:
  build:
    name: Push to morphic-i18n-central

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'test output'
        run: |
          echo "token:" ${{ secrets.API_TOKEN_GITHUB }}

      - name: crowdin action
        uses: crowdin/github-action@1.1.2
        with:
          upload_sources: true

          upload_translations: true
          upload_language: 'en'
          auto_approve_imported: true
          import_eq_suggestions: true

          download_translations: true
          download_language: 'es'
          skip_untranslated_strings: true
          skip_untranslated_files: true
          export_only_approved: true
          push_translations: true
          commit_message: 'New Crowdin translations by Github Action'

          localization_branch_name: l10n_crowdin_action
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'enhancement, good first issue'

          crowdin_branch_name: l10n_branch
          identity: '.github/workflows/i18n-sync.yml'
          config: '.github/workflows/i18n-sync.yml'
          dryrun_action: true

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}

          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: 'src/locales/en.json'
          translation: 'src/locales/%locale%/%original_file_name%'
          base_url: 'https://crowdin.com'
          base_path: 'src/locales'

        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          
          project_id_env: CROWDIN_PROJECT_ID
          api_token_env: CROWDIN_PERSONAL_TOKEN
 
      # - name: Push updated i18n file
      #   id: push_directory
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: 'src/locales'
      #     destination-github-username: 'Tushcr7'
      #     destination-repository-name: 'morphic-i18n-central'
      #     target-branch: 'community-sync-tests'
      #     # destination_folder: 'morphic-community-webapp'
      #     user-email: 'k7tushar@gmail.com'
      #     commit-message: 'Push the file'


# CROWDIN_PERSONAL_TOKEN: 8f3c15f0bd426e7bb223ff091563ae2080e52401dd5af20d6082f1a98a409bcf4c329f1d9fd403cb